import React from 'react'

export function TermsOfService() {
  return (
    <div>
      {/* Hero */}
      <div className="bg-gradient-to-b from-green-500/10 to-transparent border-b border-border py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 text-center">
          <div className="w-20 h-20 rounded-2xl overflow-hidden ring-2 ring-green-500/30 shadow-lg mx-auto mb-6">
            <img src="/logo-alt.svg" alt="ShieldNet" className="w-full h-full object-contain bg-white" />
          </div>
          <h1 className="text-4xl font-bold mb-3">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: April 18, 2026</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16">

      <div className="space-y-10 text-foreground/85">

        <section>
          <p className="text-base leading-relaxed">
            These Terms of Service ("Terms") govern your access to and use of the ShieldNetCore Technologies Ltd platform ("ShieldNet", "we", "us"), including ShieldNet AI, ShieldFarm, and ShieldNet Properties, and all related services, websites, and applications.
          </p>
          <p className="text-base leading-relaxed mt-3">
            By creating an account or accessing our platform, you agree to be bound by these Terms and our Privacy Policy. If you do not agree, you must not use our services.
          </p>
        </section>

        <Section title="1. Eligibility">
          <ul>
            <li>You must be at least 18 years of age to use ShieldNet.</li>
            <li>You must be legally capable of entering into binding contracts under Nigerian law.</li>
            <li>Businesses using ShieldNet must be duly registered under Nigerian law and represented by an authorised individual.</li>
            <li>ShieldNet reserves the right to refuse or terminate service to anyone at its sole discretion.</li>
          </ul>
        </Section>

        <Section title="2. Account Registration and Security">
          <ul>
            <li>You must provide accurate, current, and complete information during registration.</li>
            <li>You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account.</li>
            <li>You must notify us immediately at <a href="mailto:security@shieldnet.ng" className="text-green-400 hover:underline">security@shieldnet.ng</a> if you suspect unauthorised access to your account.</li>
            <li>ShieldNet will never ask for your password via email, phone, or chat.</li>
            <li>You may not create more than one personal account. Agents and businesses may have separate business accounts.</li>
          </ul>
        </Section>

        <Section title="3. ShieldNet Properties — Listing Rules">
          <Subsection title="3.1 Agent Responsibilities">
            <ul>
              <li>Only licensed or duly authorised agents and property owners may list properties on the platform.</li>
              <li>All listing information — price, location, photographs, and title documents — must be accurate and truthful.</li>
              <li>Agents must hold valid authority (power of attorney, agency agreement, or ownership proof) before listing any property.</li>
              <li>Properties pending admin review must not be marketed as "verified" until the Shield Verified badge is granted.</li>
            </ul>
          </Subsection>
          <Subsection title="3.2 Prohibited Listings">
            <ul>
              <li>Properties with disputed or fraudulent title documents.</li>
              <li>Land subject to government acquisition or compulsory purchase orders.</li>
              <li>Properties listed without the knowledge or consent of the owner.</li>
              <li>Duplicate listings of the same property at different prices.</li>
              <li>Properties used for or facilitating illegal activities.</li>
            </ul>
          </Subsection>
          <Subsection title="3.3 Buyer Protections">
            <ul>
              <li>ShieldNet's Shield Verified badge indicates that our AI and admin team have reviewed available documentation. It is not a legal guarantee of title.</li>
              <li>Buyers are advised to conduct independent legal due diligence before completing any transaction.</li>
              <li>ShieldNet is not a party to any property transaction and is not liable for losses arising from third-party transactions.</li>
            </ul>
          </Subsection>
        </Section>

        <Section title="4. ShieldFarm — Agricultural Services">
          <ul>
            <li>Crop diagnosis results are generated by AI models with high but imperfect accuracy. They are advisory in nature and do not replace professional agronomist advice.</li>
            <li>Market price data is sourced from third-party markets and is updated regularly but may not reflect real-time prices at every location.</li>
            <li>Farm diary entries and data are your property and will not be shared with third parties without your consent, except as required by law.</li>
            <li>ShieldNet is not liable for crop losses, yield shortfalls, or economic damage arising from reliance on AI diagnosis or market price data.</li>
          </ul>
        </Section>

        <Section title="5. ShieldNet AI — Security Services">
          <ul>
            <li>Shield Scores are dynamic assessments based on available data and may not reflect every aspect of a user's trustworthiness.</li>
            <li>Fraud detection alerts are probabilistic. A flagged listing does not conclusively confirm fraud; an unflagged listing is not guaranteed to be legitimate.</li>
            <li>Identity verification is performed to a commercial standard and does not constitute legal proof of identity.</li>
            <li>You must not attempt to manipulate, game, or artificially inflate your Shield Score.</li>
          </ul>
        </Section>

        <Section title="6. Prohibited Conduct">
          <p>You agree not to:</p>
          <ul>
            <li>Post false, misleading, or fraudulent information on the platform.</li>
            <li>Impersonate any person, company, or ShieldNet staff member.</li>
            <li>Use the platform to facilitate money laundering, advance-fee fraud (419), or any criminal activity.</li>
            <li>Attempt to hack, scrape, reverse-engineer, or disrupt the platform or its infrastructure.</li>
            <li>Use automated bots or scripts to create accounts, post listings, or extract data without written permission.</li>
            <li>Harass, threaten, or abuse other users or ShieldNet staff.</li>
            <li>Circumvent or disable any fraud detection, verification, or security feature.</li>
            <li>Resell or commercially exploit ShieldNet data or services without authorisation.</li>
          </ul>
          <p className="mt-3">Violation of these rules may result in immediate account suspension, permanent ban, and referral to law enforcement.</p>
        </Section>

        <Section title="7. Fraud Reporting">
          <ul>
            <li>Users are encouraged to report suspicious listings or conduct using the fraud report feature.</li>
            <li>Reports must be made in good faith. Filing a false or malicious fraud report against another user may result in account suspension.</li>
            <li>ShieldNet will investigate all reports and take appropriate action, but cannot guarantee a specific outcome or timeline.</li>
            <li>Reporter identities are kept confidential during investigations.</li>
          </ul>
        </Section>

        <Section title="8. Intellectual Property">
          <ul>
            <li>All content, trademarks, logos, software, and data on the ShieldNet platform are the intellectual property of ShieldNetCore Technologies Ltd or its licensors.</li>
            <li>You may not copy, reproduce, distribute, or create derivative works from any ShieldNet content without prior written consent.</li>
            <li>You retain ownership of content you submit (listings, photos, diary entries). By submitting content, you grant ShieldNet a non-exclusive, royalty-free licence to use, display, and process that content to provide the services.</li>
            <li>You warrant that content you submit does not infringe any third-party intellectual property rights.</li>
          </ul>
        </Section>

        <Section title="9. Fees and Payments">
          <ul>
            <li>Basic access to ShieldNet is free. Certain premium features (such as featured listings, bulk verification, or enterprise API access) may carry fees as published on our pricing page.</li>
            <li>All fees are quoted in Nigerian Naira (₦) and are inclusive of applicable taxes unless stated otherwise.</li>
            <li>Payments are non-refundable except where required by law or at ShieldNet's sole discretion.</li>
            <li>ShieldNet reserves the right to change its fee structure with 30 days' notice to registered users.</li>
          </ul>
        </Section>

        <Section title="10. Limitation of Liability">
          <p>To the maximum extent permitted by Nigerian law:</p>
          <ul>
            <li>ShieldNet provides its platform on an "as is" and "as available" basis without warranties of any kind.</li>
            <li>ShieldNet is not liable for any indirect, incidental, special, or consequential damages arising from your use of the platform.</li>
            <li>ShieldNet's total liability to you for any claim arising from your use of the platform shall not exceed the amount you paid to ShieldNet in the 12 months preceding the claim.</li>
            <li>ShieldNet is not liable for losses arising from property transactions between users, market price fluctuations, or reliance on AI-generated outputs.</li>
          </ul>
        </Section>

        <Section title="11. Indemnification">
          <p>You agree to indemnify and hold harmless ShieldNet, its officers, directors, employees, and agents from any claims, losses, damages, or expenses (including legal fees) arising from:</p>
          <ul>
            <li>Your breach of these Terms.</li>
            <li>Your violation of any applicable law or regulation.</li>
            <li>Content you submit to the platform.</li>
            <li>Any transaction or dispute between you and another user.</li>
          </ul>
        </Section>

        <Section title="12. Termination">
          <ul>
            <li>You may close your account at any time by contacting <a href="mailto:support@shieldnet.ng" className="text-green-400 hover:underline">support@shieldnet.ng</a>.</li>
            <li>ShieldNet may suspend or terminate your account immediately for breach of these Terms, fraudulent activity, or at our sole discretion with 7 days' notice for other reasons.</li>
            <li>Upon termination, your right to use the platform ceases. We may retain your data as required by law (see Privacy Policy, Section 5).</li>
          </ul>
        </Section>

        <Section title="13. Governing Law and Disputes">
          <ul>
            <li>These Terms are governed by the laws of the Federal Republic of Nigeria.</li>
            <li>Any dispute arising from these Terms shall first be subject to good-faith negotiation between the parties.</li>
            <li>If unresolved within 30 days, disputes shall be referred to arbitration under the Arbitration and Conciliation Act (as amended) in Abuja, Nigeria.</li>
            <li>Nothing in this clause prevents either party from seeking urgent injunctive relief from a Nigerian court.</li>
          </ul>
        </Section>

        <Section title="14. Changes to These Terms">
          <p>We may update these Terms from time to time. We will notify you of material changes via email or a platform notice at least 14 days before they take effect. Continued use of the platform after that date constitutes your acceptance of the updated Terms.</p>
        </Section>

        <Section title="15. Contact">
          <ul>
            <li><strong>General Enquiries:</strong> <a href="mailto:info@shieldnet.ng" className="text-green-400 hover:underline">info@shieldnet.ng</a></li>
            <li><strong>Legal / Compliance:</strong> <a href="mailto:legal@shieldnet.ng" className="text-green-400 hover:underline">legal@shieldnet.ng</a></li>
            <li><strong>Security Issues:</strong> <a href="mailto:security@shieldnet.ng" className="text-green-400 hover:underline">security@shieldnet.ng</a></li>
            <li><strong>Address:</strong> ShieldNetCore Technologies Ltd, Abuja, Federal Capital Territory, Nigeria</li>
          </ul>
        </Section>

      </div>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold mb-4 text-foreground">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-foreground/80">{children}</div>
    </section>
  )
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-4">
      <h3 className="text-base font-semibold mb-2 text-foreground">{title}</h3>
      <div className="space-y-2 text-sm leading-relaxed pl-1">{children}</div>
    </div>
  )
}
